### ISSUE TITLE
Problem with downloads on mac

### ISSUE THREAD

**Issue by Apros7** [Chrillebon/DTUMathTools#4]
Installation on mac M1/M2 does not work, as you will get an error when trying to collect PyQt5>=5.15.7.
This is due to PyQt5 not working with pip on M1/M2

To fix this problem, first run the following:
```
brew install PyQt@5
```
You might have to run it this way if your brew and other mac installation programs are not up to date:
```
xcode-select --install
brew install PyQt@5
```
This will take some time, but when it is done, then do this:
```
pip install -U dtumathtools
```
And you now have the newest version of dtumathtools.
If your python interpreter does not work do:
```
brew install python3
```
And then use ```pip3 install <package_name>``` to install packages.
Remember to select the correct interpreter in vscode

**Comment by Chrillebon** [comment]
Thank you for the insight!

Newer versions of dtumathtools do not require PyQt5 at install time, so this can be done later if using the qt backend is preferred.

If this still does not work, consider different backends as seen [here](https://sympy-plot-backends.readthedocs.io/en/latest/modules/backends/plot.html). This might require other packages to be installed. If say "plotly" is the backend of choice for 3D plots, you can also change the default backend using

dtuplot.cfg["backend_3D"] = "plotly"
dtuplot.set_defaults(dtuplot.cfg)
