### ISSUE TITLE
ImportError on _unpack_args_extended 

### ISSUE THREAD

**Issue by fnielsen** [Chrillebon/DTUMathTools#6]
I see a report on ImportError on `_unpack_args_extended` from quiverplot.py's import of `spb.utils`. In the repo version of spd.utils there is no `_unpack_args_extended`. https://github.com/Davide-sd/sympy-plot-backends/blob/master/spb/utils.py

This has been removed: https://github.com/Davide-sd/sympy-plot-backends/commit/2c255977c9abc7e09b471fd1a23bac36875fbb2e

**Comment by Chrillebon** [comment]
This is spb that has updated to a new, unsupported version. Update dtumathtools to version 1.0.5, that effectively downgrade spb to 1.6.6/1.6.7.

**Comment by Chrillebon** [comment]
Let me know if this fixes the problem.

Support for newer versions of spb is planned for next semester.

**Comment by fnielsen** [comment]
The student that had the problem says it now works
